import{S,a as $,i as f}from"./assets/vendor-53a1b719.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const m of s.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&i(m)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const x=document.querySelector(".gallery");function k(r){return r.map(e=>`<li class="gallery-item">
  <a class="gallery-link" href="${e.largeImageURL}">
    <img
      class="gallery-image"
      src="${e.webformatURL}"
      data-source="${e.largeImageURL}"
      alt="Tags: ${e.tags}. Likes: ${e.likes},   Views: ${e.views},   Comments: ${e.comments},   Downloads: ${e.downloads}"
    />
  </a>
  <div class="gallery-item-info">
  <p class="info-image"><b class="info-image-text">Likes</b><span class="info-image-number">${e.likes}</span></p>
  <p class="info-image"><b class="info-image-text">Views</b><span class="info-image-number">${e.views}</span></p>
  <p class="info-image"><b class="info-image-text">Comments</b><span class="info-image-number">${e.comments}</span></p>
  <p class="info-image"><b class="info-image-text">Downloads</b><span class="info-image-number">${e.downloads}</span></p>
  </div>
</li>`).join("")}const q=new S(".gallery a",{overlayOpacity:.8,captionsData:"alt",captionDelay:250,className:"modal-image"});function y(r){const e=k(r);x.insertAdjacentHTML("beforeend",e),q.refresh()}async function b(r,e){const o="https://pixabay.com/api/",i=new URLSearchParams({key:"20488832-3f7ee310b3351fba3525ae600",q:r,image_type:"photo",orientation:"horizontal",safesearch:"true",page:e,per_page:"15"});try{return(await $.get(`${o}?${i}`)).data}catch(t){throw new Error(t.message)}}const g="/goit-js-hw-12/assets/octagon-17638c89.svg",n=document.querySelector(".form"),E=document.querySelector(".gallery"),w=document.querySelector(".loader"),c=document.querySelector(".search-btn"),p=document.querySelector(".load-btn");let a=1,h=0,l="";c.disabled=!0;d();n.input.addEventListener("input",()=>{c.disabled=!n.input.value.trim()});n.addEventListener("submit",P);p.addEventListener("click",U);async function P(r){if(r.preventDefault(),E.innerHTML="",L(),l=r.target.elements.input.value.trim(),!l){d();return}c.disabled=!0;try{const e=await b(l,a=1);if(e&&e.hits&&e.hits.length)y(e.hits),h=Math.ceil(e.totalHits/15),a<h?v():(u(),f.error({message:"We're sorry, but you've reached the end of search results.",backgroundColor:"#EF4040",theme:"dark",iconUrl:g,maxWidth:354,messageSize:"16"}));else throw u(),new Error("Sorry, there are no images matching your search query. Please try again!")}catch(e){f.error({message:e.message,position:"topRight",backgroundColor:"#EF4040",theme:"dark",iconUrl:g,maxWidth:354,messageSize:"16"})}finally{d(),c.disabled=!0}n.reset()}async function U(r){a+=1,u(),L();try{const e=await b(l,a);if(e&&e.hits&&e.hits.length){y(e.hits);const o=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({left:0,top:o*2,behavior:"smooth"}),a<h?v():(u(),f.error({message:"We're sorry, but you've reached the end of search results.",backgroundColor:"#EF4040",theme:"dark",iconUrl:g,maxWidth:354,messageSize:"16"}))}}catch(e){alert(e.message)}finally{d()}n.reset()}function L(){w.style.display="inline-block"}function d(){w.style.display="none"}function v(){p.classList.remove("hidden")}function u(){p.classList.add("hidden")}
//# sourceMappingURL=commonHelpers.js.map
